apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-20-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-20-pod
  template:
    metadata:
      labels:
        app: edge-20-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kwok
      # A taints was added to an automatically created Node.
      # You can remove taints of Node or add this tolerations.
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: edge-container
        image: edge-image

---

apiVersion: v1
kind: Service
metadata:
  name: edge-20-service
  namespace: default
spec:
  selector:
    app: edge-20-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080